name: salam
description: A Flutter app for registering Muslim faithfuls, integrated with Frappe/ERPNext backend.
version: 1.0.0
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.7.0
  provider: ^6.1.2
  get_it: ^7.7.0
  equatable: ^2.0.5
  flutter_secure_storage: ^9.2.2
  go_router: ^14.2.8
  flutter_form_builder: ^9.3.0
  cupertino_icons: ^1.0.8
  json_annotation: ^4.9.0
  intl: ^0.19.0
  file_picker: ^10.2.0 

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.9
  json_serializable: ^6.8.0
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Amiri
      fonts:
        - asset: assets/fonts/Amiri-Regular.ttf 